export const actionTypes = {

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    /*** Fetch Posts ***/
    FETCH_POSTS_START : 'FETCH_POSTS_START',
    FETCH_POSTS_SUCCESS : 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAILURE : 'FETCH_POSTS_FAILURE',

    FETCH_POSTS_BY_LOCATION_SUCCESS : 'FETCH_POSTS_BY_LOCATION_SUCCESS',
    FETCH_POSTS_BY_LOCATION_FAILURE : 'FETCH_POSTS_BY_LOCATION_FAILURE',

    FETCH_POSTS_BY_TAG_SUCCESS : 'FETCH_POSTS_BY_TAG_SUCCESS',
    FETCH_POSTS_BY_TAG_FAILURE : 'FETCH_POSTS_BY_TAG_FAILURE',
    /*** Post Like ***/
    LIKE_POST : 'LIKE_POST',
    DISLIKE_POST : 'DISLIKE_POST',

    /*** Post Comments ***/
    ADD_COMMENT : 'ADD_COMMENT',
    DELETE_COMMENT : 'DELETE_COMMENT',

    /*** Public Profile ***/
    FETCH_PUBLIC_PROFILE_START : 'FETCH_PUBLIC_PROFILE_START',
    FETCH_PUBLIC_PROFILE_SUCCESS : 'FETCH_PUBLIC_PROFILE_SUCCESS',
    FETCH_PUBLIC_PROFILE_FAILURE : 'FETCH_PUBLIC_PROFILE_FAILURE',
    FETCH_POSTS_BY_USERNAME_START : 'FETCH_POSTS_BY_USERNAME_START',
    FETCH_POSTS_BY_USERNAME_SUCCESS : 'FETCH_POSTS_BY_USERNAME_SUCCESS',
    FETCH_POSTS_BY_USERNAME_FAILURE : 'FETCH_POSTS_BY_USERNAME_FAILURE',

    /*** Follow Users ***/
    FOLLOW_USER : 'FOLLOW_USER',
    UNFOLLOW_USER : 'UNFOLLOW_USER',

    /*** Fetch Followers/Following ***/
    FETCH_FOLLOWERS_START : 'FETCH_FOLLOWERS_START',
    FETCH_FOLLOWERS_SUCCESS : 'FETCH_FOLLOWERS_SUCCESS',
    FETCH_FOLLOWERS_FAILURE : 'FETCH_FOLLOWERS_FAILURE',
    FETCH_FOLLOWING_START : 'FETCH_FOLLOWING_START',
    FETCH_FOLLOWING_SUCCESS : 'FETCH_FOLLOWING_SUCCESS',
    FETCH_FOLLOWING_FAILURE : 'FETCH_FOLLOWING_FAILURE',

    /*** Fetch Likers ***/
    FETCH_LIKERS_START : 'FETCH_LIKERS_START',
    FETCH_LIKERS_SUCCESS : 'FETCH_LIKERS_SUCCESS',
    FETCH_LIKERS_FAILURE : 'FETCH_LIKERS_FAILURE',

    /*** Fetch Notifications ***/
    FETCH_NOTIFICATIONS_START : 'FETCH_NOTIFICATIONS_START',
    FETCH_NOTIFICATIONS_SUCCESS : 'FETCH_NOTIFICATIONS_SUCCESS',
    FETCH_NOTIFICATIONS_FAILURE : 'FETCH_NOTIFICATIONS_FAILURE',

    FETCH_NOTIFICATION_COUNT : 'FETCH_NOTIFICATION_COUNT',
    CLEAR_NOTIFICATIONS : 'CLEAR_NOTIFICATIONS',
    TOUCH_NOTIFICATION : 'TOUCH_NOTIFICATION',
    LIKE_POST_NOTIFICATION_RECEIVED : 'LIKE_POST_NOTIFICATION_RECEIVED',
    START_FOLLOWING_NOTIFICATION_RECEIVED : 'START_FOLLOWING_NOTIFICATION_RECEIVED',
    COMMENT_ON_POST_NOTIFICATION_RECEIVED : 'COMMENT_ON_POST_NOTIFICATION_RECEIVED',
    HIDE_NEW_NOTIFICATION : 'HIDE_NEW_NOTIFICATION',

    /*** Fetch more comments ***/
    FETCH_MORE_COMMENTS_SUCCUESS : 'FETCH_MORE_COMMENTS_SUCCUESS',

    /*** Fetch follow suggestions ***/
    FETCH_FOLLOW_SUGGESTIONS_START : 'FETCH_FOLLOW_SUGGESTIONS_START',
    FETCH_FOLLOW_SUGGESTIONS_SUCCESS : 'FETCH_FOLLOW_SUGGESTIONS_SUCCESS',
    FETCH_FOLLOW_SUGGESTIONS_FAILURE : 'FETCH_FOLLOW_SUGGESTIONS_FAILURE',

};

